# use this file for encrypted user/password information.
# Unencrypted values may be used in this file using standard yaml syntax
# Encrypted values must be enclosed in ![] within the quotes.

sftp:
  pass: "![kIesv6hZB222OF6Vy+3VFZaZW/UYE3CXCUVFccfBcASJ25ZxmRBaQdm0tHgaS2Du]"
  