# API specification
#Autodiscovery
  
# Listener configuration
https:
  host: "0.0.0.0"
  port: "8082"
  req:
    host: "0.0.0.0"
    port: "8083"
    api: "api"
    path: "/insert"
  email:
    host: "0.0.0.0"
    port: "8084"
    path: "/insert"
    
orders-prc-api:   
  http-listener:
    path: "/api/*"
     
sftp:
  host: "ap-southeast-1.sftpcloud.io"
  user: "e956b7f63fae441eab6eab1292e89e8b"
  port: "22" 
  
ftp:
  host: "127.0.0.1" 
  port: "21"
  user: "mule user"
  pass: "Shiri@0702"
  



